import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { SurveyModal } from "@/components/employer-survey";

export const Route = createFileRoute("/app/employer")({
  head: () => ({ meta: [{ title: "Employer Portal — Udaan" }] }),
  component: EmployerPage,
});

// ─── Types ────────────────────────────────────────────────────────────────────
type Question = { q: string; expects: string[]; hint: string };
type Interview = { id: string; candidateId: string; jobTitle: string; timestamp: string; transcript: { q: string; a: string; gesture?: string }[] };

// ─── PDF Generator (pure JS, no library needed) ────────────────────────────
function downloadTranscriptPDF(interview: Interview) {
  // Build clean HTML then use window.print trick via a new window
  const lines = interview.transcript.map((t, i) =>
    `<div style="margin-bottom:16px;page-break-inside:avoid">
      <p style="font-size:11px;color:#666;margin:0 0 2px">Q${i+1}: ${t.q}</p>
      <p style="font-size:14px;font-weight:700;margin:0;background:#f5f5f5;padding:8px 12px;border-radius:6px">💬 ${t.a}</p>
    </div>`
  ).join("");

  const html = `
    <!DOCTYPE html><html><head>
      <title>Interview Transcript — ${interview.jobTitle}</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 680px; margin: 40px auto; color: #111; }
        h1 { font-size: 22px; margin-bottom: 4px; }
        .meta { font-size: 13px; color: #555; margin-bottom: 24px; border-bottom: 1px solid #ddd; padding-bottom: 12px; }
        .footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 11px; color: #999; }
      </style>
    </head><body>
      <h1>📋 Interview Transcript</h1>
      <div class="meta">
        <strong>Job:</strong> ${interview.jobTitle} &nbsp;|&nbsp;
        <strong>Candidate:</strong> ${interview.candidateId} &nbsp;|&nbsp;
        <strong>Date:</strong> ${new Date(interview.timestamp).toLocaleString("en-IN")}
      </div>
      ${lines}
      <div class="footer">Generated by Udaan · Sign Language Interview Platform</div>
    </body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 500);
}

// ─── Component ────────────────────────────────────────────────────────────────
function EmployerPage() {
  const [tab, setTab] = useState<"create" | "applications">("create");
  const employerId = localStorage.getItem("db_user_id") || "emp_1";

  // Form state
  const [title, setTitle] = useState("");
  const [company, setCompany] = useState("");
  const [description, setDescription] = useState("");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [newQ, setNewQ] = useState("");
  const [posting, setPosting] = useState(false);
  const [postSuccess, setPostSuccess] = useState(false);

  // Applications state
  const [interviews, setInterviews] = useState<Interview[]>([]);
  const [loadingInt, setLoadingInt] = useState(false);
  const [showSurvey, setShowSurvey] = useState(false);
  const [hasBadge, setHasBadge] = useState(false);
  const [inclusionFlags, setInclusionFlags] = useState<Record<number, boolean>>({});

  useEffect(() => {
    const saved = localStorage.getItem("db_employer_badge");
    if (saved === "true") setHasBadge(true);
    
    const savedFlags = localStorage.getItem("db_inclusion_flags");
    if (savedFlags) setInclusionFlags(JSON.parse(savedFlags));

    if (!saved && !localStorage.getItem("db_survey_skipped")) setShowSurvey(true);
  }, []);

  const handleSurveyComplete = (score: number, answers: Record<number, boolean>) => {
    const earned = score >= 70; // 70% threshold for badge
    setHasBadge(earned);
    setInclusionFlags(answers);
    if (earned) localStorage.setItem("db_employer_badge", "true");
    localStorage.setItem("db_inclusion_flags", JSON.stringify(answers));
    setShowSurvey(false);
  };

  useEffect(() => {
    if (tab === "applications") loadInterviews();
  }, [tab]);

  async function loadInterviews() {
    setLoadingInt(true);
    try {
      const res = await fetch(`http://localhost:5000/api/interviews/employer/${employerId}`);
      if (res.ok) setInterviews(await res.json());
    } catch {}
    setLoadingInt(false);
  }

  function addQuestion() {
    if (!newQ.trim()) return;
    setQuestions(q => [...q, { q: newQ.trim(), expects: ["yes", "no"], hint: "🖐 Open palm = Yes • ✊ Fist = No" }]);
    setNewQ("");
  }

  function removeQuestion(i: number) {
    setQuestions(q => q.filter((_, idx) => idx !== i));
  }

  async function postJob(e: React.FormEvent) {
    e.preventDefault();
    setPosting(true);
    try {
      const res = await fetch("http://localhost:5000/api/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          title, 
          company, 
          description, 
          employerId, 
          questions, 
          hasBadge: hasBadge ? 1 : 0,
          inclusionFlags: JSON.stringify(inclusionFlags)
        }),
      });
      if (res.ok) {
        setPostSuccess(true);
        setTitle(""); setCompany(""); setDescription(""); setQuestions([]);
        setTimeout(() => { setPostSuccess(false); setTab("applications"); }, 1500);
      }
    } catch {}
    setPosting(false);
  }

  return (
    <div className="min-h-screen bg-[#f8f9fa] text-gray-900">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-8 py-5 flex items-center justify-between sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <span className="text-3xl">🌉</span>
          <div>
            <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider">Udaan</p>
            <h1 className="text-xl font-black text-gray-900">Employer Portal</h1>
          </div>
        </div>
        <div className="flex items-center gap-4">
          {/* Tab switcher */}
          <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
            <button
              onClick={() => setTab("create")}
              className={`px-4 py-2 rounded-lg font-bold text-sm transition ${tab === "create" ? "bg-white shadow text-gray-900" : "text-gray-500 hover:text-gray-700"}`}
            >
              ＋ Create Interview
            </button>
            <button
              onClick={() => setTab("applications")}
              className={`px-4 py-2 rounded-lg font-bold text-sm transition ${tab === "applications" ? "bg-white shadow text-gray-900" : "text-gray-500 hover:text-gray-700"}`}
            >
              📥 Applications {interviews.length > 0 && `(${interviews.length})`}
            </button>
          </div>
          <button
            onClick={() => { localStorage.removeItem("db_session"); window.location.href = "/auth/sign-in"; }}
            className="text-sm font-semibold text-gray-500 hover:text-gray-900 transition"
          >
            Log out
          </button>
          <button
            onClick={() => {
              localStorage.removeItem("db_employer_badge");
              localStorage.removeItem("db_inclusion_flags");
              localStorage.removeItem("db_survey_skipped");
              window.location.reload();
            }}
            className="text-xs font-bold text-blue-600 hover:underline"
          >
            Retake Inclusion Audit
          </button>
        </div>
      </header>

      <SurveyModal 
        open={showSurvey} 
        onOpenChange={setShowSurvey} 
        onComplete={handleSurveyComplete} 
      />

      <main className="max-w-4xl mx-auto px-6 py-10">

        {/* ── Create Job Tab ───────────────────────────────────── */}
        {tab === "create" && (
          <div>
            <div className="mb-8">
              <h2 className="text-2xl font-black">Create a Job Interview</h2>
              <p className="text-gray-500 mt-1">Post a job and define the sign language interview questions. PWD candidates will see your listing and answer via hand gestures.</p>
            </div>

            {postSuccess && (
              <div className="mb-6 bg-green-50 text-green-800 border border-green-200 rounded-2xl p-4 font-bold text-center">
                ✅ Job posted successfully! Redirecting to Applications…
              </div>
            )}

            <form onSubmit={postJob} className="bg-white rounded-2xl border border-gray-200 shadow-sm p-8 space-y-6">
              <div className="grid md:grid-cols-2 gap-5">
                <div>
                  <label className="block font-bold text-sm mb-2">Job Title *</label>
                  <input
                    required value={title} onChange={e => setTitle(e.target.value)}
                    className="w-full border-2 border-gray-200 rounded-xl px-4 py-3 focus:border-blue-500 outline-none transition"
                    placeholder="e.g. Frontend Developer"
                  />
                </div>
                <div>
                  <label className="block font-bold text-sm mb-2">Company Name *</label>
                  <input
                    required value={company} onChange={e => setCompany(e.target.value)}
                    className="w-full border-2 border-gray-200 rounded-xl px-4 py-3 focus:border-blue-500 outline-none transition"
                    placeholder="e.g. Tech4Good Pvt Ltd"
                  />
                </div>
              </div>

              <div>
                <label className="block font-bold text-sm mb-2">Job Description</label>
                <textarea
                  rows={3} value={description} onChange={e => setDescription(e.target.value)}
                  className="w-full border-2 border-gray-200 rounded-xl px-4 py-3 focus:border-blue-500 outline-none transition resize-none"
                  placeholder="Describe the role, responsibilities, and any accommodations provided…"
                />
              </div>

              {/* Questions */}
              <div className="border-t-2 border-gray-100 pt-6">
                <h3 className="font-black text-lg mb-1">Sign Language Interview Questions</h3>
                <p className="text-sm text-gray-500 mb-4">
                  Candidates will answer these using hand gestures (Open palm = Yes, Fist = No, Thumbs up = Confident, etc.)
                </p>

                {questions.length > 0 && (
                  <ul className="space-y-2 mb-4">
                    {questions.map((q, i) => (
                      <li key={i} className="flex items-start gap-3 bg-gray-50 rounded-xl p-3">
                        <span className="bg-blue-100 text-blue-700 font-black text-xs px-2 py-1 rounded mt-0.5">Q{i + 1}</span>
                        <span className="flex-1 font-semibold text-sm">{q.q}</span>
                        <button type="button" onClick={() => removeQuestion(i)} className="text-gray-400 hover:text-red-500 text-lg leading-none transition">×</button>
                      </li>
                    ))}
                  </ul>
                )}

                <div className="flex gap-2">
                  <input
                    value={newQ} onChange={e => setNewQ(e.target.value)}
                    onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addQuestion())}
                    className="flex-1 border-2 border-gray-200 rounded-xl px-4 py-3 focus:border-blue-500 outline-none transition"
                    placeholder="Type a question (e.g. Are you available on weekends?)"
                  />
                  <button
                    type="button" onClick={addQuestion}
                    className="bg-gray-100 hover:bg-gray-200 font-bold px-5 rounded-xl transition"
                  >
                    ＋ Add
                  </button>
                </div>
              </div>

              <button
                type="submit" disabled={posting}
                className="w-full bg-blue-600 text-white font-black py-4 rounded-xl hover:bg-blue-700 disabled:opacity-50 transition text-lg"
              >
                {posting ? "Posting…" : "Post Job & Activate Interview →"}
              </button>
            </form>
          </div>
        )}

        {/* ── Applications Tab ─────────────────────────────────── */}
        {tab === "applications" && (
          <div>
            <div className="flex items-end justify-between mb-8">
              <div>
                <h2 className="text-2xl font-black">Candidate Applications</h2>
                <p className="text-gray-500 mt-1">Sign language interview transcripts submitted by PWD candidates.</p>
              </div>
              <button onClick={loadInterviews} className="text-sm font-semibold text-blue-600 hover:underline">
                ↻ Refresh
              </button>
            </div>

            {loadingInt && (
              <div className="text-center py-16 text-gray-400">
                <p className="text-4xl mb-3 animate-pulse">📥</p>
                <p className="font-semibold">Loading applications…</p>
              </div>
            )}

            {!loadingInt && interviews.length === 0 && (
              <div className="text-center py-20 bg-white rounded-2xl border border-gray-200">
                <p className="text-5xl mb-4">📭</p>
                <p className="text-xl font-black text-gray-700">No applications yet</p>
                <p className="text-gray-400 mt-2">Post a job interview and wait for PWD candidates to apply.</p>
                <button onClick={() => setTab("create")} className="mt-6 bg-blue-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-blue-700 transition">
                  Create Your First Interview →
                </button>
              </div>
            )}

            <div className="space-y-5">
              {interviews.map(int => (
                <article key={int.id} className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
                  {/* Card header */}
                  <div className="px-6 py-4 bg-gray-50 border-b border-gray-100 flex items-center justify-between">
                    <div>
                      <h3 className="font-black text-lg">{int.jobTitle}</h3>
                      <p className="text-sm text-gray-500">
                        Candidate: <strong className="text-gray-700">{int.candidateId}</strong>
                        &nbsp;·&nbsp;
                        {new Date(int.timestamp).toLocaleString("en-IN")}
                      </p>
                    </div>
                    <button
                      onClick={() => downloadTranscriptPDF(int)}
                      className="flex items-center gap-2 bg-blue-600 text-white font-bold px-4 py-2 rounded-xl hover:bg-blue-700 transition text-sm"
                    >
                      ⬇ Download PDF
                    </button>
                  </div>

                  {/* Transcript */}
                  <div className="px-6 py-5 space-y-4">
                    {int.transcript.map((t, i) => (
                      <div key={i}>
                        <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Q{i+1}</p>
                        <p className="font-semibold text-sm text-gray-700 mb-1">{t.q}</p>
                        <div className="bg-gray-50 rounded-xl px-4 py-3 text-sm font-bold text-gray-900">
                          💬 {t.a}
                        </div>
                      </div>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
