import { createFileRoute, Link } from "@tanstack/react-router";
import * as React from "react";
import { useA11y } from "@/lib/accessibility-context";
import { QRCodeSVG } from "qrcode.react";

export const Route = createFileRoute("/app/wallet")({
  head: () => ({ meta: [{ title: "Digital Wallet — DisabilityBridge" }] }),
  component: DigitalWalletPage,
});

function DigitalWalletPage() {
  const a11y = useA11y();
  const [appData, setAppData] = React.useState<any>(null);
  const [loading, setLoading] = React.useState(true);
  const [tapping, setTapping] = React.useState(false);
  const [receipt, setReceipt] = React.useState<string | null>(null);

  const userId = typeof window !== "undefined" ? localStorage.getItem("db_user_id") : null;

  React.useEffect(() => {
    if (userId) {
      fetch(`http://localhost:5000/api/udid/user/${userId}`)
        .then(res => {
          if (!res.ok) throw new Error("No app");
          return res.json();
        })
        .then(data => {
          setAppData(data);
          setLoading(false);
          if (data?.status === "Card Generated") {
            a11y.speak("Digital Wallet loaded. Your e-UDID card is ready to use.", "assistant");
          }
        })
        .catch(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, [userId]);

  const simulateNFCTap = async () => {
    if (!appData?.id) return;
    setTapping(true);
    setReceipt(null);
    a11y.speak("Simulating NFC tap...", "assistant");
    
    try {
      const res = await fetch(`http://localhost:5000/api/udid/verify-tap/${appData.id}`, {
        method: "POST"
      });
      const data = await res.json();
      
      if (data.success) {
        setTimeout(() => {
          setReceipt(data.receipt);
          setTapping(false);
          a11y.speak("Card verified successfully via NFC tap.", "system");
        }, 1500); // delay for dramatic effect
      } else {
        throw new Error(data.error);
      }
    } catch (err) {
      setTapping(false);
      a11y.speak("NFC verification failed.", "system");
      alert("Verification failed.");
    }
  };

  if (loading) {
    return <div className="p-10 text-center font-bold text-xl">Loading Digital Wallet...</div>;
  }

  // State 1: No Application
  if (!appData) {
    return (
      <div className="max-w-2xl mx-auto space-y-8 text-center py-20">
        <div className="text-8xl mb-6">🪪</div>
        <h1 className="text-4xl font-black tracking-tight">Digital Wallet</h1>
        <p className="text-muted-foreground text-xl">
          You don't have an active UDID application. Apply for your Unique Disability ID to unlock your digital wallet.
        </p>
        <Link 
          to="/app/udid"
          className="inline-block bg-primary text-primary-foreground px-8 py-4 rounded-2xl font-black text-lg shadow-xl hover:scale-105 transition"
        >
          Go to UDID Navigator
        </Link>
      </div>
    );
  }

  // State 2: Application Processing
  if (appData.status !== "Card Generated") {
    return (
      <div className="max-w-2xl mx-auto space-y-8 text-center py-20">
        <div className="text-8xl mb-6 opacity-50">⏳</div>
        <h1 className="text-4xl font-black tracking-tight">Card Generating</h1>
        <p className="text-muted-foreground text-xl">
          Your UDID application is currently: <strong className="text-primary">{appData.status}</strong>.
        </p>
        <p className="text-sm font-bold">
          Once approved and generated by the Government, your digital card will appear here automatically.
        </p>
        <div className="p-6 bg-muted rounded-3xl border-2 border-border mt-8 text-left">
          <p className="font-bold text-sm text-muted-foreground mb-2">Application ID</p>
          <p className="font-black text-2xl">{appData.id}</p>
        </div>
      </div>
    );
  }

  // State 3: Card Generated
  return (
    <div className="max-w-3xl mx-auto space-y-8 pb-32">
      <header>
        <h1 className="text-4xl font-black tracking-tight">🪪 Digital Wallet</h1>
        <p className="text-muted-foreground mt-1 text-lg">Present this card for concessions or use NFC tap at government counters.</p>
      </header>

      {/* The ID Card */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 via-blue-600 to-primary text-white shadow-2xl border-4 border-white/20 p-8 sm:p-10 transform transition-transform hover:scale-[1.02]">
        {/* Glassmorphic overlays */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3"></div>
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-black/10 rounded-full blur-3xl translate-y-1/3 -translate-x-1/3"></div>
        
        <div className="relative z-10 flex flex-col md:flex-row justify-between gap-8">
          <div className="flex-1 space-y-6">
            <div>
              <div className="flex items-center gap-2 mb-1 opacity-90">
                <span className="text-2xl">🇮🇳</span>
                <span className="text-sm font-bold uppercase tracking-widest">Government of India</span>
              </div>
              <h2 className="text-3xl font-black leading-tight drop-shadow-md">Unique Disability ID</h2>
            </div>
            
            <div className="space-y-4">
              <div>
                <p className="text-xs font-bold text-white/70 uppercase tracking-wider mb-1">Cardholder Name</p>
                <p className="text-2xl font-black drop-shadow-sm">{appData.name}</p>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs font-bold text-white/70 uppercase tracking-wider mb-1">Disability Type</p>
                  <p className="text-lg font-bold">{appData.disabilityType}</p>
                </div>
                <div>
                  <p className="text-xs font-bold text-white/70 uppercase tracking-wider mb-1">UDID Number</p>
                  <p className="text-lg font-bold font-mono">{appData.id}</p>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex flex-col items-center justify-center bg-white p-4 rounded-3xl shadow-inner shrink-0 self-start md:self-center">
            <QRCodeSVG value={`udid:${appData.id}:${appData.name}`} size={140} level="H" />
            <p className="text-[10px] font-black text-black/50 mt-2 tracking-widest uppercase">Scan to Verify</p>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-card rounded-3xl border-2 border-border p-6 shadow-sm">
          <h3 className="font-black text-lg mb-4 flex items-center gap-2">
            <span className="text-2xl">⚡</span> Quick Concessions
          </h3>
          <div className="grid grid-cols-2 gap-3">
            <button className="flex flex-col items-center justify-center p-4 bg-muted hover:bg-primary/10 hover:text-primary rounded-2xl border border-transparent hover:border-primary/20 transition font-bold text-sm">
              <span className="text-3xl mb-2">🚂</span> Railway
            </button>
            <button className="flex flex-col items-center justify-center p-4 bg-muted hover:bg-primary/10 hover:text-primary rounded-2xl border border-transparent hover:border-primary/20 transition font-bold text-sm">
              <span className="text-3xl mb-2">🚌</span> Bus Pass
            </button>
            <button className="flex flex-col items-center justify-center p-4 bg-muted hover:bg-primary/10 hover:text-primary rounded-2xl border border-transparent hover:border-primary/20 transition font-bold text-sm">
              <span className="text-3xl mb-2">🏥</span> Hospital Queue
            </button>
            <button className="flex flex-col items-center justify-center p-4 bg-muted hover:bg-primary/10 hover:text-primary rounded-2xl border border-transparent hover:border-primary/20 transition font-bold text-sm">
              <span className="text-3xl mb-2">📉</span> Tax Rebate
            </button>
          </div>
        </div>

        <div className="bg-card rounded-3xl border-2 border-primary/20 p-6 shadow-sm flex flex-col justify-center items-center text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-2xl"></div>
          
          {receipt ? (
            <div className="animate-in zoom-in duration-300">
              <div className="w-20 h-20 bg-green-500 text-white rounded-full flex items-center justify-center text-4xl mx-auto mb-4 shadow-lg shadow-green-500/30">
                ✓
              </div>
              <h3 className="font-black text-xl text-green-600 mb-1">Verified Successfully</h3>
              <p className="text-xs font-mono font-bold text-muted-foreground bg-muted px-3 py-1 rounded-full">{receipt}</p>
              <button 
                onClick={() => setReceipt(null)}
                className="mt-4 text-sm font-bold text-primary underline"
              >
                Tap again
              </button>
            </div>
          ) : (
            <>
              <h3 className="font-black text-lg mb-2">Government Counters</h3>
              <p className="text-sm text-muted-foreground font-bold mb-6">Hold your phone near the NFC reader at participating government desks to instantly verify your identity.</p>
              
              <button 
                onClick={simulateNFCTap}
                disabled={tapping}
                className={`relative w-full max-w-xs py-4 rounded-2xl font-black text-lg shadow-xl transition-all ${
                  tapping 
                    ? "bg-primary text-primary-foreground animate-pulse" 
                    : "bg-primary text-primary-foreground hover:scale-105"
                }`}
              >
                {tapping ? "Contacting Terminal..." : "📶 Tap to Verify (Mock)"}
                {tapping && (
                  <span className="absolute inset-0 rounded-2xl border-4 border-primary animate-ping opacity-50"></span>
                )}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
