import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect } from "react";

export const Route = createFileRoute("/employer")({
  head: () => ({ meta: [{ title: "Employer Portal — DisabilityBridge" }] }),
  component: EmployerPortal,
});

// ─── Types ───────────────────────────────────────────────────────────────────
type Question = { q: string };
type InterviewRecord = {
  id: string;
  candidateId: string;
  jobTitle: string;
  timestamp: string;
  transcript: { q: string; a: string }[];
};

// ─── PDF Download (pure browser, no library) ─────────────────────────────────
function downloadPDF(record: InterviewRecord) {
  const rows = record.transcript
    .map(
      (t, i) => `
      <div style="margin-bottom:20px;page-break-inside:avoid">
        <p style="margin:0 0 4px;font-size:11px;color:#888;text-transform:uppercase;letter-spacing:.05em">Question ${i + 1}</p>
        <p style="margin:0 0 6px;font-size:14px;font-weight:700;color:#111">${t.q}</p>
        <div style="background:#f0f4ff;border-left:3px solid #3b5bdb;padding:10px 14px;border-radius:0 8px 8px 0;font-size:14px;color:#222">
          💬 ${t.a}
        </div>
      </div>`
    )
    .join("");

  const html = `<!DOCTYPE html><html><head>
    <meta charset="utf-8">
    <title>Interview Transcript</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Segoe UI', Arial, sans-serif; color: #111; padding: 48px 56px; max-width: 720px; margin: auto; }
      .header { border-bottom: 2px solid #e9ecef; padding-bottom: 20px; margin-bottom: 32px; }
      .badge { display:inline-block; background:#3b5bdb; color:#fff; font-size:11px; font-weight:700; padding:3px 10px; border-radius:20px; margin-bottom:12px; letter-spacing:.04em; }
      h1 { font-size: 24px; font-weight: 900; color: #111; margin-bottom: 6px; }
      .meta { font-size: 13px; color: #666; }
      .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e9ecef; font-size: 11px; color: #aaa; text-align: center; }
      @media print { body { padding: 24px 32px; } }
    </style>
  </head><body>
    <div class="header">
      <div class="badge">DISABILITY BRIDGE · INTERVIEW TRANSCRIPT</div>
      <h1>${record.jobTitle}</h1>
      <p class="meta">
        <strong>Candidate:</strong> ${record.candidateId} &nbsp;·&nbsp;
        <strong>Submitted:</strong> ${new Date(record.timestamp).toLocaleString("en-IN", { dateStyle: "long", timeStyle: "short" })}
      </p>
    </div>
    ${rows}
    <div class="footer">Generated by DisabilityBridge Sign Language Interview Platform · Confidential</div>
  </body></html>`;

  const win = window.open("", "_blank", "width=800,height=900");
  if (!win) return alert("Allow popups to download the PDF");
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 600);
}

// ─── Main Component ───────────────────────────────────────────────────────────
function EmployerPortal() {
  const [tab, setTab] = useState<"create" | "applications">("create");

  // Form fields
  const [jobTitle, setJobTitle] = useState("");
  const [company, setCompany] = useState("");
  const [description, setDescription] = useState("");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [newQ, setNewQ] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState("");

  // Applications
  const [interviews, setInterviews] = useState<InterviewRecord[]>([]);
  const [loadingApps, setLoadingApps] = useState(false);

  useEffect(() => {
    if (tab === "applications") fetchApplications();
  }, [tab]);

  async function fetchApplications() {
    setLoadingApps(true);
    try {
      const res = await fetch("http://localhost:5000/api/interviews/employer/emp_1");
      if (res.ok) setInterviews(await res.json());
    } catch { /* backend may not respond */ }
    setLoadingApps(false);
  }

  function addQuestion() {
    const q = newQ.trim();
    if (!q) return;
    setQuestions(prev => [...prev, { q }]);
    setNewQ("");
  }

  function removeQuestion(i: number) {
    setQuestions(prev => prev.filter((_, idx) => idx !== i));
  }

  async function handlePostJob(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setSaveMsg("");
    try {
      const res = await fetch("http://localhost:5000/api/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: jobTitle,
          company,
          description,
          employerId: "emp_1",
          questions: questions.map(q => ({
            q: q.q,
            expects: ["yes", "no"],
            hint: "🖐 Open palm = Yes • ✊ Fist = No",
          })),
        }),
      });
      if (res.ok) {
        setSaveMsg("✅ Job posted! Candidates can now see it and take the sign interview.");
        setJobTitle(""); setCompany(""); setDescription(""); setQuestions([]);
      } else {
        setSaveMsg("❌ Failed to post job. Is the backend running?");
      }
    } catch {
      setSaveMsg("❌ Could not reach backend (localhost:5000). Start the server.");
    }
    setSaving(false);
  }

  function logout() {
    localStorage.removeItem("db_session");
    window.location.href = "/auth/sign-in";
  }

  return (
    <div style={{ minHeight: "100vh", background: "#f8fafc", fontFamily: "'Segoe UI', Arial, sans-serif", color: "#111" }}>

      {/* ── Top Nav ─────────────────────────────────────────────── */}
      <nav style={{ background: "#fff", borderBottom: "1px solid #e2e8f0", padding: "0 40px", display: "flex", alignItems: "center", height: 64, gap: 12 }}>
        <span style={{ fontSize: 28 }}>🌉</span>
        <div style={{ flex: 1 }}>
          <span style={{ fontSize: 13, color: "#94a3b8", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em" }}>DisabilityBridge</span>
          <span style={{ fontSize: 13, color: "#94a3b8", marginLeft: 8 }}>/ Employer Portal</span>
        </div>

        {/* Tab pills */}
        <div style={{ display: "flex", background: "#f1f5f9", borderRadius: 12, padding: 4, gap: 4 }}>
          {(["create", "applications"] as const).map(t => (
            <button
              key={t}
              onClick={() => setTab(t)}
              style={{
                padding: "8px 20px",
                borderRadius: 8,
                border: "none",
                cursor: "pointer",
                fontWeight: 700,
                fontSize: 14,
                background: tab === t ? "#fff" : "transparent",
                color: tab === t ? "#1e293b" : "#64748b",
                boxShadow: tab === t ? "0 1px 4px rgba(0,0,0,.08)" : "none",
                transition: "all .15s",
              }}
            >
              {t === "create" ? "＋ Create Job" : `📥 Applications${interviews.length ? ` (${interviews.length})` : ""}`}
            </button>
          ))}
        </div>

        <button
          onClick={logout}
          style={{ marginLeft: 16, fontSize: 14, fontWeight: 600, color: "#64748b", background: "none", border: "none", cursor: "pointer" }}
        >
          Log out
        </button>
      </nav>

      <main style={{ maxWidth: 860, margin: "0 auto", padding: "40px 24px" }}>

        {/* ── CREATE TAB ───────────────────────────────────────── */}
        {tab === "create" && (
          <div>
            <h1 style={{ fontSize: 28, fontWeight: 900, marginBottom: 6 }}>Post a Job Interview</h1>
            <p style={{ color: "#64748b", marginBottom: 32, fontSize: 15 }}>
              Fill in the job details and add your interview questions. PWD candidates will see the listing,
              answer each question via sign language, and submit their transcript directly to you.
            </p>

            {saveMsg && (
              <div style={{
                marginBottom: 24, padding: "14px 18px", borderRadius: 12,
                background: saveMsg.startsWith("✅") ? "#f0fdf4" : "#fff1f2",
                border: `1px solid ${saveMsg.startsWith("✅") ? "#bbf7d0" : "#fecaca"}`,
                color: saveMsg.startsWith("✅") ? "#15803d" : "#dc2626",
                fontWeight: 700, fontSize: 15,
              }}>
                {saveMsg}
              </div>
            )}

            <form onSubmit={handlePostJob} style={{ background: "#fff", borderRadius: 20, border: "1px solid #e2e8f0", padding: 36, boxShadow: "0 2px 12px rgba(0,0,0,.04)" }}>

              {/* Basic info */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }}>
                <div>
                  <label style={{ display: "block", fontWeight: 700, fontSize: 13, marginBottom: 6, color: "#374151" }}>Job Title *</label>
                  <input
                    required value={jobTitle} onChange={e => setJobTitle(e.target.value)}
                    placeholder="e.g. Frontend Developer"
                    style={{ width: "100%", padding: "12px 16px", borderRadius: 12, border: "2px solid #e2e8f0", fontSize: 15, outline: "none", boxSizing: "border-box" }}
                    onFocus={e => (e.target.style.borderColor = "#3b5bdb")}
                    onBlur={e => (e.target.style.borderColor = "#e2e8f0")}
                  />
                </div>
                <div>
                  <label style={{ display: "block", fontWeight: 700, fontSize: 13, marginBottom: 6, color: "#374151" }}>Company Name *</label>
                  <input
                    required value={company} onChange={e => setCompany(e.target.value)}
                    placeholder="e.g. Tech4Good Pvt Ltd"
                    style={{ width: "100%", padding: "12px 16px", borderRadius: 12, border: "2px solid #e2e8f0", fontSize: 15, outline: "none", boxSizing: "border-box" }}
                    onFocus={e => (e.target.style.borderColor = "#3b5bdb")}
                    onBlur={e => (e.target.style.borderColor = "#e2e8f0")}
                  />
                </div>
              </div>

              <div style={{ marginBottom: 28 }}>
                <label style={{ display: "block", fontWeight: 700, fontSize: 13, marginBottom: 6, color: "#374151" }}>Description</label>
                <textarea
                  value={description} onChange={e => setDescription(e.target.value)}
                  rows={3}
                  placeholder="Describe responsibilities and any disability accommodations provided…"
                  style={{ width: "100%", padding: "12px 16px", borderRadius: 12, border: "2px solid #e2e8f0", fontSize: 15, outline: "none", resize: "vertical", boxSizing: "border-box" }}
                  onFocus={e => (e.target.style.borderColor = "#3b5bdb")}
                  onBlur={e => (e.target.style.borderColor = "#e2e8f0")}
                />
              </div>

              {/* Questions section */}
              <div style={{ borderTop: "2px solid #f1f5f9", paddingTop: 28 }}>
                <h2 style={{ fontSize: 18, fontWeight: 900, marginBottom: 4 }}>Sign Language Interview Questions</h2>
                <p style={{ fontSize: 13, color: "#64748b", marginBottom: 20 }}>
                  Each question will be shown to the PWD candidate during their interview. They answer using hand gestures (Yes/No/Thumbs up/Peace/Point/ILY).
                </p>

                {/* Question list */}
                {questions.length > 0 && (
                  <ul style={{ marginBottom: 16, listStyle: "none", padding: 0, display: "flex", flexDirection: "column", gap: 8 }}>
                    {questions.map((q, i) => (
                      <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: 10, background: "#f8fafc", borderRadius: 12, padding: "12px 16px", border: "1px solid #e2e8f0" }}>
                        <span style={{ background: "#3b5bdb", color: "#fff", fontSize: 11, fontWeight: 900, padding: "2px 8px", borderRadius: 20, marginTop: 2, whiteSpace: "nowrap" }}>Q{i + 1}</span>
                        <span style={{ flex: 1, fontSize: 14, fontWeight: 600 }}>{q.q}</span>
                        <button type="button" onClick={() => removeQuestion(i)} style={{ background: "none", border: "none", cursor: "pointer", color: "#94a3b8", fontSize: 20, lineHeight: 1, padding: 0 }}>×</button>
                      </li>
                    ))}
                  </ul>
                )}

                {/* Add question */}
                <div style={{ display: "flex", gap: 10 }}>
                  <input
                    value={newQ} onChange={e => setNewQ(e.target.value)}
                    onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addQuestion())}
                    placeholder="Type a question… (press Enter or click Add)"
                    style={{ flex: 1, padding: "12px 16px", borderRadius: 12, border: "2px solid #e2e8f0", fontSize: 15, outline: "none" }}
                    onFocus={e => (e.target.style.borderColor = "#3b5bdb")}
                    onBlur={e => (e.target.style.borderColor = "#e2e8f0")}
                  />
                  <button
                    type="button" onClick={addQuestion}
                    style={{ padding: "12px 22px", borderRadius: 12, border: "2px solid #e2e8f0", background: "#f8fafc", fontWeight: 700, fontSize: 15, cursor: "pointer" }}
                  >
                    ＋ Add
                  </button>
                </div>
              </div>

              <button
                type="submit" disabled={saving}
                style={{
                  marginTop: 32, width: "100%", padding: "16px", borderRadius: 14,
                  background: saving ? "#94a3b8" : "#3b5bdb", color: "#fff",
                  fontWeight: 900, fontSize: 17, border: "none", cursor: saving ? "not-allowed" : "pointer",
                  transition: "background .2s",
                }}
              >
                {saving ? "Posting…" : "Post Job & Activate Sign Interview →"}
              </button>
            </form>
          </div>
        )}

        {/* ── APPLICATIONS TAB ─────────────────────────────────── */}
        {tab === "applications" && (
          <div>
            <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 32 }}>
              <div>
                <h1 style={{ fontSize: 28, fontWeight: 900, marginBottom: 4 }}>Candidate Applications</h1>
                <p style={{ color: "#64748b", fontSize: 15 }}>Sign language interview transcripts submitted by PWD candidates.</p>
              </div>
              <button onClick={fetchApplications} style={{ background: "none", border: "none", color: "#3b5bdb", fontWeight: 700, cursor: "pointer", fontSize: 14 }}>
                ↻ Refresh
              </button>
            </div>

            {loadingApps && (
              <div style={{ textAlign: "center", padding: "80px 0", color: "#94a3b8" }}>
                <div style={{ fontSize: 48, marginBottom: 12 }}>📥</div>
                <p style={{ fontWeight: 600, fontSize: 16 }}>Loading applications…</p>
              </div>
            )}

            {!loadingApps && interviews.length === 0 && (
              <div style={{ textAlign: "center", padding: "80px 40px", background: "#fff", borderRadius: 20, border: "1px solid #e2e8f0" }}>
                <div style={{ fontSize: 56, marginBottom: 16 }}>📭</div>
                <p style={{ fontSize: 20, fontWeight: 900, color: "#374151", marginBottom: 8 }}>No applications yet</p>
                <p style={{ color: "#94a3b8", marginBottom: 24 }}>Post a job interview and PWD candidates will submit their sign language responses here.</p>
                <button onClick={() => setTab("create")} style={{ background: "#3b5bdb", color: "#fff", border: "none", borderRadius: 12, padding: "12px 28px", fontWeight: 700, fontSize: 15, cursor: "pointer" }}>
                  Create Your First Interview →
                </button>
              </div>
            )}

            <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
              {interviews.map(int => (
                <article key={int.id} style={{ background: "#fff", borderRadius: 20, border: "1px solid #e2e8f0", overflow: "hidden", boxShadow: "0 2px 12px rgba(0,0,0,.04)" }}>
                  {/* Card header */}
                  <div style={{ background: "#f8fafc", borderBottom: "1px solid #e2e8f0", padding: "18px 28px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                    <div>
                      <h3 style={{ fontSize: 18, fontWeight: 900, marginBottom: 4 }}>{int.jobTitle}</h3>
                      <p style={{ fontSize: 13, color: "#64748b" }}>
                        Candidate: <strong style={{ color: "#374151" }}>{int.candidateId}</strong>
                        &nbsp;·&nbsp;
                        {new Date(int.timestamp).toLocaleString("en-IN")}
                      </p>
                    </div>
                    <button
                      onClick={() => downloadPDF(int)}
                      style={{
                        display: "flex", alignItems: "center", gap: 8,
                        background: "#3b5bdb", color: "#fff", border: "none",
                        borderRadius: 10, padding: "10px 20px", fontWeight: 700,
                        fontSize: 14, cursor: "pointer",
                      }}
                    >
                      ⬇ Download PDF
                    </button>
                  </div>

                  {/* Transcript */}
                  <div style={{ padding: "24px 28px", display: "flex", flexDirection: "column", gap: 20 }}>
                    {int.transcript.map((t, i) => (
                      <div key={i}>
                        <p style={{ fontSize: 11, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 }}>Q{i + 1}</p>
                        <p style={{ fontSize: 14, fontWeight: 700, color: "#374151", marginBottom: 8 }}>{t.q}</p>
                        <div style={{ background: "#f0f4ff", borderLeft: "3px solid #3b5bdb", padding: "10px 16px", borderRadius: "0 10px 10px 0", fontSize: 14, color: "#1e293b", fontWeight: 600 }}>
                          💬 {t.a}
                        </div>
                      </div>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
