export const EMPLOYER_SURVEY_QUESTIONS = [
  "Does your workplace have step-free access or ramps at all entrances?",
  "Are the ramps compliant with proper slope and handrails?",
  "Are there accessible washrooms with grab bars and adequate space?",
  "Are elevators available with Braille buttons and audio announcements?",
  "Is there reserved accessible parking near the entrance?",
  "Is your company website screen-reader compatible?",
  "Are internal HR tools and software accessible to visually impaired users?",
  "Do your digital platforms support keyboard-only navigation?",
  "Are training materials provided with captions or transcripts?",
  "Do you follow recognized accessibility standards like WCAG?",
  "Does your organization have a formal disability inclusion policy?",
  "Have employees undergone disability sensitivity training?",
  "Do you provide reasonable accommodations such as flexible hours or assistive devices?",
  "Is there a designated liaison officer for employees with disabilities?",
  "Do you have an anti-discrimination policy covering disabilities?",
  "Do you actively encourage persons with disabilities to apply in job postings?",
  "Is your hiring process accessible (e.g., interpreters, extra time, alternative formats)?",
  "What percentage of your workforce consists of UDID-certified employees?",
  "Do you track and report hiring and retention metrics for persons with disabilities?",
  "Do you partner with organizations supporting disability employment?",
];
